// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: SentBody.proto

package proto

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SentBodyModel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Data          map[string]string      `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SentBodyModel) Reset() {
	*x = SentBodyModel{}
	mi := &file_SentBody_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SentBodyModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SentBodyModel) ProtoMessage() {}

func (x *SentBodyModel) ProtoReflect() protoreflect.Message {
	mi := &file_SentBody_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SentBodyModel.ProtoReflect.Descriptor instead.
func (*SentBodyModel) Descriptor() ([]byte, []int) {
	return file_SentBody_proto_rawDescGZIP(), []int{0}
}

func (x *SentBodyModel) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *SentBodyModel) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *SentBodyModel) GetData() map[string]string {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_SentBody_proto protoreflect.FileDescriptor

const file_SentBody_proto_rawDesc = "" +
	"\n" +
	"\x0eSentBody.proto\"\xa6\x01\n" +
	"\rSentBodyModel\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x12,\n" +
	"\x04data\x18\x03 \x03(\v2\x18.SentBodyModel.DataEntryR\x04data\x1a7\n" +
	"\tDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\x15Z\x13./sentbody;sentbodyb\x06proto3"

var (
	file_SentBody_proto_rawDescOnce sync.Once
	file_SentBody_proto_rawDescData []byte
)

func file_SentBody_proto_rawDescGZIP() []byte {
	file_SentBody_proto_rawDescOnce.Do(func() {
		file_SentBody_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_SentBody_proto_rawDesc), len(file_SentBody_proto_rawDesc)))
	})
	return file_SentBody_proto_rawDescData
}

var file_SentBody_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_SentBody_proto_goTypes = []any{
	(*SentBodyModel)(nil), // 0: SentBodyModel
	nil,                   // 1: SentBodyModel.DataEntry
}
var file_SentBody_proto_depIdxs = []int32{
	1, // 0: SentBodyModel.data:type_name -> SentBodyModel.DataEntry
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_SentBody_proto_init() }
func file_SentBody_proto_init() {
	if File_SentBody_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_SentBody_proto_rawDesc), len(file_SentBody_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_SentBody_proto_goTypes,
		DependencyIndexes: file_SentBody_proto_depIdxs,
		MessageInfos:      file_SentBody_proto_msgTypes,
	}.Build()
	File_SentBody_proto = out.File
	file_SentBody_proto_goTypes = nil
	file_SentBody_proto_depIdxs = nil
}
