// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: ReplyBody.proto

package proto

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReplyBodyModel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Timestamp     int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Data          map[string]string      `protobuf:"bytes,5,rep,name=data,proto3" json:"data,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplyBodyModel) Reset() {
	*x = ReplyBodyModel{}
	mi := &file_ReplyBody_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplyBodyModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplyBodyModel) ProtoMessage() {}

func (x *ReplyBodyModel) ProtoReflect() protoreflect.Message {
	mi := &file_ReplyBody_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplyBodyModel.ProtoReflect.Descriptor instead.
func (*ReplyBodyModel) Descriptor() ([]byte, []int) {
	return file_ReplyBody_proto_rawDescGZIP(), []int{0}
}

func (x *ReplyBodyModel) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ReplyBodyModel) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ReplyBodyModel) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ReplyBodyModel) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *ReplyBodyModel) GetData() map[string]string {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_ReplyBody_proto protoreflect.FileDescriptor

const file_ReplyBody_proto_rawDesc = "" +
	"\n" +
	"\x0fReplyBody.proto\"\xd6\x01\n" +
	"\x0eReplyBodyModel\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\x12-\n" +
	"\x04data\x18\x05 \x03(\v2\x19.ReplyBodyModel.DataEntryR\x04data\x1a7\n" +
	"\tDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\x17Z\x15./replybody;replybodyb\x06proto3"

var (
	file_ReplyBody_proto_rawDescOnce sync.Once
	file_ReplyBody_proto_rawDescData []byte
)

func file_ReplyBody_proto_rawDescGZIP() []byte {
	file_ReplyBody_proto_rawDescOnce.Do(func() {
		file_ReplyBody_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ReplyBody_proto_rawDesc), len(file_ReplyBody_proto_rawDesc)))
	})
	return file_ReplyBody_proto_rawDescData
}

var file_ReplyBody_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_ReplyBody_proto_goTypes = []any{
	(*ReplyBodyModel)(nil), // 0: ReplyBodyModel
	nil,                    // 1: ReplyBodyModel.DataEntry
}
var file_ReplyBody_proto_depIdxs = []int32{
	1, // 0: ReplyBodyModel.data:type_name -> ReplyBodyModel.DataEntry
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_ReplyBody_proto_init() }
func file_ReplyBody_proto_init() {
	if File_ReplyBody_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ReplyBody_proto_rawDesc), len(file_ReplyBody_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ReplyBody_proto_goTypes,
		DependencyIndexes: file_ReplyBody_proto_depIdxs,
		MessageInfos:      file_ReplyBody_proto_msgTypes,
	}.Build()
	File_ReplyBody_proto = out.File
	file_ReplyBody_proto_goTypes = nil
	file_ReplyBody_proto_depIdxs = nil
}
